"""empty message

Revision ID: b36074f3fe0a
Revises: 
Create Date: 2023-03-30 20:53:50.444148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b36074f3fe0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_table('phonenumber',
    sa.Column('number_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('number_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phonenumber')
    op.drop_table('person')
    # ### end Alembic commands ###
